---
- name: Install nifi
  hosts: all
  vars: 
      nifi_log_level_root: WARN
      nifi_node_jvm_memory: '10240M'
      nifi_custom_nars: [ '/opt/extra-nars' ]
      nifi_single_node: True
      nifi_authorized_nodes_list: ['nifi-node-1', 'nifi-node-2']
  become: yes
  become_user: root
  
  pre_tasks:
    - name: Upgrade all
      yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*
        
  roles:
  - role: java
  - role: nifi-old
    nifi_version: 1.14.0
